# Generated by Django 3.0.7 on 2020-06-03 14:16

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subscription_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Дата оформления подписки')),
                ('cost', models.CharField(choices=[('1', '1 month'), ('2', '2 month'), ('3', '3 month')], default='1 month', max_length=12)),
                ('subscription_end_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Конец подписки')),
                ('status', models.BooleanField(default=False, verbose_name='Стату подписки : ')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='users/%Y/%m/%d')),
                ('role', models.CharField(blank=True, max_length=8, verbose_name='Роль: ')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format.', regex='^\\+?1?\\d{9,15}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
