# Generated by Django 3.0.7 on 2020-06-03 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=255, verbose_name='Название операции')),
                ('operation_summ', models.PositiveIntegerField(verbose_name='Сумма')),
            ],
        ),
        migrations.CreateModel(
            name='Personalaccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('summ', models.PositiveIntegerField(default=0, verbose_name='Сумма в рублях')),
            ],
        ),
        migrations.CreateModel(
            name='Popoln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.FloatField(default=50.0, verbose_name='Сумма')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата покупки')),
                ('odobren', models.BooleanField(default=False, verbose_name='Успех пополнения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пополнение',
                'verbose_name_plural': 'Пополнения',
                'db_table': 'popoln',
            },
        ),
    ]
