# Generated by Django 3.0.7 on 2020-06-03 14:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('presentation', models.TextField(verbose_name='Описание проекта')),
                ('choices', models.CharField(choices=[('Selling', 'Selling'), ('Investing', 'Investing')], default='investing', max_length=15)),
                ('full_project_description', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Полное описание проекта')),
                ('business_plan', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Бизнес план')),
                ('project_img_one', models.ImageField(blank=True, upload_to='uploads/images/%Y/%m/%d/')),
                ('project_img_two', models.ImageField(blank=True, upload_to='uploads/images/%Y/%m/%d/')),
                ('project_img_three', models.ImageField(blank=True, upload_to='uploads/images/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=130)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('project_cost', models.PositiveIntegerField(help_text='Указывать сумму в рублях', verbose_name='Стоимость проекта')),
                ('project_investment', models.PositiveIntegerField(help_text='Указывать сумму в рублях', verbose_name='Сумма инвестиции')),
                ('universality', models.BooleanField(default=False, verbose_name='Универсальность проека')),
                ('status_active_of_project', models.BooleanField(default=False, verbose_name='Статус активности проекта')),
                ('publication_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Дата публикации')),
                ('promotions', models.BooleanField(default=False, verbose_name='Продвижение проекта')),
                ('payment_state', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('project_comletion', models.BooleanField(default=False, verbose_name='Статус завершения проекта')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectManager.Category', verbose_name='Категория')),
                ('project_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectaAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Project')),
            ],
            options={
                'db_table': 'ProjectaAnalytics',
            },
        ),
    ]
